### PR TITLE
Adds a place holder for when the bug image is nil

### PR DESCRIPTION
**Pull request by MorganRodgers**
Addresses #10.
On the internet connections I've used so far things download too quickly to reasonably test this, so I explicitly set the image to ```nil```. Search for the phrase ```LOOK HERE TO TEST``` to find where those settings are.

### CODE REVIEW

**Comment by pclemins** [comment]
Looks good... but, do you think the image should say "Image Downloading" instead of "Image Not Available"?

**Comment by MorganRodgers** [comment]
Possible states for an image are: ok, and not. Reasons for those states include: URL 404'd, or 500'd, image is still queued for download, the WikiEducator server is down, the image is malformed, and probably others. Only in one of those cases should we suggest to the user that they should expect to get the image.

How about modifying the message to: Image Not Currently Available? I think that better encompasses the messages:

- We cannot show you this image right now
- We might be able to later

We could provide image placeholders for different states including Image Downloading and Image Failed To Download?

**Comment by pclemins** [comment]
Good point... how about this:

2 Placeholders: "Images Downloading" and one other... either "Image Failed
to Download" or "Image Not Currently Available"... your choice.

Add a status boolean to WebData.m that we set to true at the start of the
Image Download method and false at the end.  When that status boolean
variable is true, we use "Images Downloading" and when it's false, the
other.

Make sense?

**Comment by MorganRodgers** [comment]
I've created two new placeholders (which may need resizing) and will work them in.

Image Queued For Download
Image Unavailable

**Pull request merged**
